# Generated by Django 4.0.6 on 2022-12-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
    ]
